---
abstract: 'Excludes untracked files from your dist'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  Archive::Tar: 0
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Git-ExcludeUntracked
requires:
  Dist::Zilla: 0
  perl: v5.8.8
resources:
  bugtracker: https://github.com/hoelzro/dist-zilla-plugin-git-excludeuntracked/issues
  homepage: https://github.com/hoelzro/dist-zilla-plugin-git-excludeuntracked
  repository: https://github.com/hoelzro/dist-zilla-plugin-git-excludeuntracked.git
version: 0.02
